require: rubocop-jekyll

inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - script/**/*
    - vendor/**/*

Metrics/AbcSize:
  Exclude:
    - lib/jekyll-commonmark.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/jekyll-commonmark.rb

Metrics/MethodLength:
  Exclude:
    - lib/jekyll-commonmark.rb

Metrics/LineLength:
  Exclude:
    - lib/jekyll-commonmark.rb

Lint/Debugger:
  Exclude:
    - script/console

Metrics/BlockLength:
  Exclude:
    - spec/**/*
